// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yesqehrxdkcrixjrsxpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllc3FlaHJ4ZGtjcml4anJzeHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzODg2MzUsImV4cCI6MjA4OTk2NDYzNX0.smT3h1jfmvsMhJc9nonHE5KQLCR-u7lhX5hxR-J9Ios";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});